org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Ditambahkan untuk memperbaiki error build:
# "Could not close incremental caches ... this and base files have different roots"
# (pub cache ada di drive C:, project ada di drive D:).
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
